"""
Curated list of RSS feeds organized by category.
"""

FEEDS = [
    # ── World News ─────────────────────────────────────────────────────────
    {
        "name": "BBC World News",
        "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "category": "world",
        "source": "BBC",
        "emoji": "🌍",
    },
    {
        "name": "Reuters Top News",
        "url": "https://feeds.reuters.com/reuters/topNews",
        "category": "world",
        "source": "Reuters",
        "emoji": "📡",
    },
    {
        "name": "Al Jazeera English",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "category": "world",
        "source": "Al Jazeera",
        "emoji": "🌐",
    },
    {
        "name": "The Guardian World",
        "url": "https://www.theguardian.com/world/rss",
        "category": "world",
        "source": "The Guardian",
        "emoji": "📰",
    },
    {
        "name": "Associated Press",
        "url": "https://feeds.apnews.com/rss/apf-topnews",
        "category": "world",
        "source": "AP News",
        "emoji": "🗞️",
    },
    {
        "name": "NPR World",
        "url": "https://feeds.npr.org/1004/rss.xml",
        "category": "world",
        "source": "NPR",
        "emoji": "📻",
    },
    {
        "name": "Deutsche Welle",
        "url": "https://rss.dw.com/rdf/rss-en-world",
        "category": "world",
        "source": "DW",
        "emoji": "🇩🇪",
    },
    {
        "name": "France 24",
        "url": "https://www.france24.com/en/rss",
        "category": "world",
        "source": "France24",
        "emoji": "🗼",
    },
    {
        "name": "CBC News World",
        "url": "https://www.cbc.ca/cmlink/rss-world",
        "category": "world",
        "source": "CBC",
        "emoji": "🍁",
    },
    {
        "name": "Voice of America",
        "url": "https://www.voanews.com/api/zqmogimmiq",
        "category": "world",
        "source": "VOA",
        "emoji": "🇺🇸",
    },
    {
        "name": "NHK World",
        "url": "https://www3.nhk.or.jp/rss/news/cat0.xml",
        "category": "world",
        "source": "NHK",
        "emoji": "🗾",
    },
    {
        "name": "South China Morning Post",
        "url": "https://www.scmp.com/rss/91/feed",
        "category": "world",
        "source": "SCMP",
        "emoji": "🇭🇰",
    },
    {
        "name": "Euronews",
        "url": "https://www.euronews.com/rss",
        "category": "world",
        "source": "Euronews",
        "emoji": "🇪🇺",
    },
    {
        "name": "The Hindu",
        "url": "https://www.thehindu.com/news/international/feeder/default.rss",
        "category": "world",
        "source": "The Hindu",
        "emoji": "🇮🇳",
    },
    {
        "name": "ABC Australia",
        "url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "category": "world",
        "source": "ABC AU",
        "emoji": "🦘",
    },

    # ── Technology ─────────────────────────────────────────────────────────
    {
        "name": "TechCrunch",
        "url": "https://techcrunch.com/feed/",
        "category": "technology",
        "source": "TechCrunch",
        "emoji": "💻",
    },
    {
        "name": "Ars Technica",
        "url": "https://feeds.arstechnica.com/arstechnica/index",
        "category": "technology",
        "source": "Ars Technica",
        "emoji": "🔬",
    },
    {
        "name": "The Verge",
        "url": "https://www.theverge.com/rss/index.xml",
        "category": "technology",
        "source": "The Verge",
        "emoji": "⚡",
    },
    {
        "name": "Wired",
        "url": "https://www.wired.com/feed/rss",
        "category": "technology",
        "source": "Wired",
        "emoji": "🔌",
    },
    {
        "name": "Hacker News",
        "url": "https://news.ycombinator.com/rss",
        "category": "technology",
        "source": "Hacker News",
        "emoji": "🟠",
    },
    {
        "name": "MIT Technology Review",
        "url": "https://www.technologyreview.com/feed/",
        "category": "technology",
        "source": "MIT Tech Review",
        "emoji": "🎓",
    },
    {
        "name": "Engadget",
        "url": "https://www.engadget.com/rss.xml",
        "category": "technology",
        "source": "Engadget",
        "emoji": "📱",
    },
    {
        "name": "VentureBeat",
        "url": "https://venturebeat.com/feed/",
        "category": "technology",
        "source": "VentureBeat",
        "emoji": "🚀",
    },
    {
        "name": "CNET",
        "url": "https://www.cnet.com/rss/news/",
        "category": "technology",
        "source": "CNET",
        "emoji": "📺",
    },
    {
        "name": "ZDNet",
        "url": "https://www.zdnet.com/news/rss.xml",
        "category": "technology",
        "source": "ZDNet",
        "emoji": "🖥️",
    },
    {
        "name": "The Register",
        "url": "https://www.theregister.com/headlines.atom",
        "category": "technology",
        "source": "The Register",
        "emoji": "🇬🇧",
    },
    {
        "name": "9to5Mac",
        "url": "https://9to5mac.com/feed/",
        "category": "technology",
        "source": "9to5Mac",
        "emoji": "🍎",
    },
    {
        "name": "9to5Google",
        "url": "https://9to5google.com/feed/",
        "category": "technology",
        "source": "9to5Google",
        "emoji": "🤖",
    },
    {
        "name": "GitHub Blog",
        "url": "https://github.blog/feed/",
        "category": "technology",
        "source": "GitHub",
        "emoji": "🐙",
    },
    {
        "name": "Stack Overflow Blog",
        "url": "https://stackoverflow.blog/feed/",
        "category": "technology",
        "source": "Stack Overflow",
        "emoji": "📚",
    },
    {
        "name": "Lobsters",
        "url": "https://lobste.rs/rss",
        "category": "technology",
        "source": "Lobsters",
        "emoji": "🦞",
    },

    # ── AI ─────────────────────────────────────────────────────────────────
    {
        "name": "OpenAI Blog",
        "url": "https://openai.com/news/rss.xml",
        "category": "ai",
        "source": "OpenAI",
        "emoji": "🤖",
    },
    {
        "name": "Google DeepMind",
        "url": "https://deepmind.google/blog/rss.xml",
        "category": "ai",
        "source": "DeepMind",
        "emoji": "🧠",
    },
    {
        "name": "Anthropic News",
        "url": "https://www.anthropic.com/news/rss.xml",
        "category": "ai",
        "source": "Anthropic",
        "emoji": "✨",
    },
    {
        "name": "Hugging Face Blog",
        "url": "https://huggingface.co/blog/feed.xml",
        "category": "ai",
        "source": "Hugging Face",
        "emoji": "🤗",
    },
    {
        "name": "VentureBeat AI",
        "url": "https://venturebeat.com/category/ai/feed/",
        "category": "ai",
        "source": "VentureBeat",
        "emoji": "💡",
    },
    {
        "name": "MIT News — AI",
        "url": "https://news.mit.edu/rss/topic/artificial-intelligence2",
        "category": "ai",
        "source": "MIT News",
        "emoji": "🎓",
    },
    {
        "name": "The Gradient",
        "url": "https://thegradient.pub/rss/",
        "category": "ai",
        "source": "The Gradient",
        "emoji": "📐",
    },
    {
        "name": "Import AI",
        "url": "https://importai.substack.com/feed",
        "category": "ai",
        "source": "Import AI",
        "emoji": "📩",
    },
    {
        "name": "Ars Technica AI",
        "url": "https://feeds.arstechnica.com/arstechnica/features",
        "category": "ai",
        "source": "Ars Technica",
        "emoji": "🔭",
    },
    {
        "name": "Wired AI",
        "url": "https://www.wired.com/feed/tag/ai/rss",
        "category": "ai",
        "source": "Wired",
        "emoji": "🌐",
    },
    {
        "name": "Last Week in AI",
        "url": "https://lastweekin.ai/feed",
        "category": "ai",
        "source": "Last Week in AI",
        "emoji": "📅",
    },

    # ── Science ────────────────────────────────────────────────────────────
    {
        "name": "BBC Science & Environment",
        "url": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "category": "science",
        "source": "BBC",
        "emoji": "🧬",
    },
    {
        "name": "NASA Breaking News",
        "url": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        "category": "science",
        "source": "NASA",
        "emoji": "🚀",
    },
    {
        "name": "New Scientist",
        "url": "https://www.newscientist.com/feed/home/",
        "category": "science",
        "source": "New Scientist",
        "emoji": "🔭",
    },
    {
        "name": "Scientific American",
        "url": "https://www.scientificamerican.com/platform/syndication/rss/",
        "category": "science",
        "source": "Sci Am",
        "emoji": "⚗️",
    },
    {
        "name": "Nature News",
        "url": "https://www.nature.com/nature.rss",
        "category": "science",
        "source": "Nature",
        "emoji": "🌿",
    },
    {
        "name": "Quanta Magazine",
        "url": "https://www.quantamagazine.org/feed/",
        "category": "science",
        "source": "Quanta",
        "emoji": "⚛️",
    },
    {
        "name": "ScienceDaily",
        "url": "https://www.sciencedaily.com/rss/top/science.xml",
        "category": "science",
        "source": "ScienceDaily",
        "emoji": "🔬",
    },
    {
        "name": "Phys.org",
        "url": "https://phys.org/rss-feed/",
        "category": "science",
        "source": "Phys.org",
        "emoji": "⚡",
    },
    {
        "name": "Space.com",
        "url": "https://www.space.com/feeds/all",
        "category": "science",
        "source": "Space.com",
        "emoji": "🌌",
    },
    {
        "name": "Science News",
        "url": "https://www.sciencenews.org/feed",
        "category": "science",
        "source": "Science News",
        "emoji": "📋",
    },
    {
        "name": "EurekAlert",
        "url": "https://www.eurekalert.org/rss.xml",
        "category": "science",
        "source": "EurekAlert",
        "emoji": "💡",
    },
    {
        "name": "Live Science",
        "url": "https://www.livescience.com/feeds/all",
        "category": "science",
        "source": "Live Science",
        "emoji": "🦋",
    },
    {
        "name": "Smithsonian Magazine",
        "url": "https://www.smithsonianmag.com/rss/science-nature/",
        "category": "science",
        "source": "Smithsonian",
        "emoji": "🏛️",
    },

    # ── Climate ────────────────────────────────────────────────────────────
    {
        "name": "The Guardian Environment",
        "url": "https://www.theguardian.com/environment/rss",
        "category": "climate",
        "source": "The Guardian",
        "emoji": "🌱",
    },
    {
        "name": "Carbon Brief",
        "url": "https://www.carbonbrief.org/feed/",
        "category": "climate",
        "source": "Carbon Brief",
        "emoji": "🌡️",
    },
    {
        "name": "Inside Climate News",
        "url": "https://insideclimatenews.org/feed/",
        "category": "climate",
        "source": "Inside Climate News",
        "emoji": "🌊",
    },
    {
        "name": "Grist",
        "url": "https://grist.org/feed/",
        "category": "climate",
        "source": "Grist",
        "emoji": "♻️",
    },
    {
        "name": "Yale Environment 360",
        "url": "https://e360.yale.edu/feed",
        "category": "climate",
        "source": "Yale E360",
        "emoji": "🎓",
    },
    {
        "name": "Canary Media",
        "url": "https://www.canarymedia.com/rss",
        "category": "climate",
        "source": "Canary Media",
        "emoji": "🐦",
    },
    {
        "name": "Climate Home News",
        "url": "https://www.climatechangenews.com/feed/",
        "category": "climate",
        "source": "Climate Home",
        "emoji": "🏠",
    },
    {
        "name": "BBC Environment",
        "url": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "category": "climate",
        "source": "BBC",
        "emoji": "🌍",
    },
    {
        "name": "DeSmog",
        "url": "https://www.desmog.com/feed/",
        "category": "climate",
        "source": "DeSmog",
        "emoji": "🔍",
    },
    {
        "name": "E&E News",
        "url": "https://www.eenews.net/rss/feed",
        "category": "climate",
        "source": "E&E News",
        "emoji": "⚡",
    },

    # ── Business ───────────────────────────────────────────────────────────
    {
        "name": "BBC Business",
        "url": "https://feeds.bbci.co.uk/news/business/rss.xml",
        "category": "business",
        "source": "BBC",
        "emoji": "📊",
    },
    {
        "name": "The Guardian Business",
        "url": "https://www.theguardian.com/business/rss",
        "category": "business",
        "source": "The Guardian",
        "emoji": "💼",
    },
    {
        "name": "CNBC Top News",
        "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "category": "business",
        "source": "CNBC",
        "emoji": "💰",
    },
    {
        "name": "Bloomberg Markets",
        "url": "https://feeds.bloomberg.com/markets/news.rss",
        "category": "business",
        "source": "Bloomberg",
        "emoji": "📈",
    },
    {
        "name": "Reuters Business",
        "url": "https://feeds.reuters.com/reuters/businessNews",
        "category": "business",
        "source": "Reuters",
        "emoji": "📡",
    },
    {
        "name": "Fast Company",
        "url": "https://www.fastcompany.com/latest/rss",
        "category": "business",
        "source": "Fast Company",
        "emoji": "⚡",
    },
    {
        "name": "Fortune",
        "url": "https://fortune.com/feed",
        "category": "business",
        "source": "Fortune",
        "emoji": "🏅",
    },
    {
        "name": "Inc.",
        "url": "https://www.inc.com/rss",
        "category": "business",
        "source": "Inc.",
        "emoji": "🏢",
    },
    {
        "name": "Harvard Business Review",
        "url": "https://feeds.hbr.org/harvardbusiness",
        "category": "business",
        "source": "HBR",
        "emoji": "📖",
    },
    {
        "name": "Quartz",
        "url": "https://qz.com/feed",
        "category": "business",
        "source": "Quartz",
        "emoji": "💎",
    },
    {
        "name": "Axios Business",
        "url": "https://api.axios.com/feed/",
        "category": "business",
        "source": "Axios",
        "emoji": "🔆",
    },

    # ── Finance ────────────────────────────────────────────────────────────
    {
        "name": "MarketWatch",
        "url": "https://feeds.marketwatch.com/marketwatch/topstories/",
        "category": "finance",
        "source": "MarketWatch",
        "emoji": "📉",
    },
    {
        "name": "Investopedia",
        "url": "https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_articles",
        "category": "finance",
        "source": "Investopedia",
        "emoji": "📚",
    },
    {
        "name": "Reuters Finance",
        "url": "https://feeds.reuters.com/reuters/financialsNews",
        "category": "finance",
        "source": "Reuters",
        "emoji": "💵",
    },
    {
        "name": "CNBC Finance",
        "url": "https://www.cnbc.com/id/10000664/device/rss/rss.html",
        "category": "finance",
        "source": "CNBC",
        "emoji": "📊",
    },
    {
        "name": "The Motley Fool",
        "url": "https://www.fool.com/feeds/index.aspx",
        "category": "finance",
        "source": "Motley Fool",
        "emoji": "🃏",
    },
    {
        "name": "CoinDesk",
        "url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "category": "finance",
        "source": "CoinDesk",
        "emoji": "₿",
    },
    {
        "name": "Decrypt",
        "url": "https://decrypt.co/feed",
        "category": "finance",
        "source": "Decrypt",
        "emoji": "🔐",
    },
    {
        "name": "Bloomberg Technology",
        "url": "https://feeds.bloomberg.com/technology/news.rss",
        "category": "finance",
        "source": "Bloomberg",
        "emoji": "💹",
    },
    {
        "name": "Financial Times",
        "url": "https://www.ft.com/rss/home/uk",
        "category": "finance",
        "source": "FT",
        "emoji": "🗞️",
    },

    # ── Health ─────────────────────────────────────────────────────────────
    {
        "name": "BBC Health",
        "url": "https://feeds.bbci.co.uk/news/health/rss.xml",
        "category": "health",
        "source": "BBC",
        "emoji": "❤️",
    },
    {
        "name": "The Guardian Health",
        "url": "https://www.theguardian.com/society/health/rss",
        "category": "health",
        "source": "The Guardian",
        "emoji": "🏥",
    },
    {
        "name": "Medical News Today",
        "url": "https://www.medicalnewstoday.com/rss/news.xml",
        "category": "health",
        "source": "MNT",
        "emoji": "💊",
    },
    {
        "name": "Harvard Health Blog",
        "url": "https://www.health.harvard.edu/blog/feed",
        "category": "health",
        "source": "Harvard Health",
        "emoji": "🩺",
    },
    {
        "name": "STAT News",
        "url": "https://www.statnews.com/feed/",
        "category": "health",
        "source": "STAT",
        "emoji": "⚕️",
    },
    {
        "name": "WebMD Health News",
        "url": "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC",
        "category": "health",
        "source": "WebMD",
        "emoji": "🔵",
    },
    {
        "name": "WHO News",
        "url": "https://www.who.int/rss-feeds/news-english.xml",
        "category": "health",
        "source": "WHO",
        "emoji": "🌐",
    },
    {
        "name": "NIH News",
        "url": "https://www.nih.gov/news-events/feed.rss",
        "category": "health",
        "source": "NIH",
        "emoji": "🔬",
    },
    {
        "name": "Healthline",
        "url": "https://www.healthline.com/rss/health-news",
        "category": "health",
        "source": "Healthline",
        "emoji": "💪",
    },
    {
        "name": "Reuters Health",
        "url": "https://feeds.reuters.com/reuters/healthNews",
        "category": "health",
        "source": "Reuters",
        "emoji": "📡",
    },

    # ── Sports ─────────────────────────────────────────────────────────────
    {
        "name": "BBC Sport",
        "url": "https://feeds.bbci.co.uk/sport/rss.xml",
        "category": "sports",
        "source": "BBC",
        "emoji": "⚽",
    },
    {
        "name": "ESPN",
        "url": "https://www.espn.com/espn/rss/news",
        "category": "sports",
        "source": "ESPN",
        "emoji": "🏆",
    },
    {
        "name": "The Guardian Sport",
        "url": "https://www.theguardian.com/sport/rss",
        "category": "sports",
        "source": "The Guardian",
        "emoji": "🎽",
    },
    {
        "name": "Sky Sports",
        "url": "https://www.skysports.com/rss/12040",
        "category": "sports",
        "source": "Sky Sports",
        "emoji": "🔵",
    },
    {
        "name": "Bleacher Report",
        "url": "https://bleacherreport.com/articles/feed",
        "category": "sports",
        "source": "B/R",
        "emoji": "📋",
    },
    {
        "name": "Sports Illustrated",
        "url": "https://www.si.com/rss/si_topstories.rss",
        "category": "sports",
        "source": "SI",
        "emoji": "🎯",
    },
    {
        "name": "Goal.com",
        "url": "https://www.goal.com/feeds/en/news",
        "category": "sports",
        "source": "Goal.com",
        "emoji": "⚽",
    },
    {
        "name": "ESPN Cricinfo",
        "url": "https://www.espncricinfo.com/rss/content/story/feeds/0.xml",
        "category": "sports",
        "source": "Cricinfo",
        "emoji": "🏏",
    },
    {
        "name": "FourFourTwo",
        "url": "https://www.fourfourtwo.com/rss",
        "category": "sports",
        "source": "FourFourTwo",
        "emoji": "🏟️",
    },
    {
        "name": "NBA.com News",
        "url": "https://www.nba.com/rss/nba_rss.xml",
        "category": "sports",
        "source": "NBA",
        "emoji": "🏀",
    },

    # ── Entertainment ──────────────────────────────────────────────────────
    {
        "name": "BBC Entertainment & Arts",
        "url": "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
        "category": "entertainment",
        "source": "BBC",
        "emoji": "🎬",
    },
    {
        "name": "Variety",
        "url": "https://variety.com/feed/",
        "category": "entertainment",
        "source": "Variety",
        "emoji": "🎭",
    },
    {
        "name": "The Guardian Culture",
        "url": "https://www.theguardian.com/culture/rss",
        "category": "entertainment",
        "source": "The Guardian",
        "emoji": "🎨",
    },
    {
        "name": "Pitchfork",
        "url": "https://pitchfork.com/feed/feed-news/rss",
        "category": "entertainment",
        "source": "Pitchfork",
        "emoji": "🎵",
    },
    {
        "name": "The Hollywood Reporter",
        "url": "https://www.hollywoodreporter.com/feed/",
        "category": "entertainment",
        "source": "THR",
        "emoji": "🌟",
    },
    {
        "name": "Rolling Stone",
        "url": "https://www.rollingstone.com/feed/",
        "category": "entertainment",
        "source": "Rolling Stone",
        "emoji": "🎸",
    },
    {
        "name": "IGN",
        "url": "https://feeds.ign.com/ign/all",
        "category": "entertainment",
        "source": "IGN",
        "emoji": "🎮",
    },
    {
        "name": "Polygon",
        "url": "https://www.polygon.com/rss/index.xml",
        "category": "entertainment",
        "source": "Polygon",
        "emoji": "🕹️",
    },
    {
        "name": "Deadline Hollywood",
        "url": "https://deadline.com/feed/",
        "category": "entertainment",
        "source": "Deadline",
        "emoji": "⏰",
    },
    {
        "name": "The A.V. Club",
        "url": "https://www.avclub.com/rss",
        "category": "entertainment",
        "source": "AV Club",
        "emoji": "📺",
    },
    {
        "name": "Kotaku",
        "url": "https://kotaku.com/rss",
        "category": "entertainment",
        "source": "Kotaku",
        "emoji": "👾",
    },
    {
        "name": "IndieWire",
        "url": "https://www.indiewire.com/feed/",
        "category": "entertainment",
        "source": "IndieWire",
        "emoji": "🎞️",
    },
    {
        "name": "Consequence",
        "url": "https://consequence.net/feed/",
        "category": "entertainment",
        "source": "Consequence",
        "emoji": "🎤",
    },

    # ── Politics ───────────────────────────────────────────────────────────
    {
        "name": "BBC Politics",
        "url": "https://feeds.bbci.co.uk/news/politics/rss.xml",
        "category": "politics",
        "source": "BBC",
        "emoji": "🏛️",
    },
    {
        "name": "The Guardian Politics",
        "url": "https://www.theguardian.com/politics/rss",
        "category": "politics",
        "source": "The Guardian",
        "emoji": "🗳️",
    },
    {
        "name": "Politico",
        "url": "https://www.politico.com/rss/politics08.xml",
        "category": "politics",
        "source": "Politico",
        "emoji": "🏟️",
    },
    {
        "name": "NPR Politics",
        "url": "https://feeds.npr.org/1014/rss.xml",
        "category": "politics",
        "source": "NPR",
        "emoji": "📻",
    },
    {
        "name": "The Hill",
        "url": "https://thehill.com/feed/",
        "category": "politics",
        "source": "The Hill",
        "emoji": "🏔️",
    },
    {
        "name": "RealClearPolitics",
        "url": "https://www.realclearpolitics.com/index.xml",
        "category": "politics",
        "source": "RCP",
        "emoji": "⚖️",
    },
    {
        "name": "Foreign Affairs",
        "url": "https://www.foreignaffairs.com/rss.xml",
        "category": "politics",
        "source": "Foreign Affairs",
        "emoji": "🌐",
    },
    {
        "name": "Council on Foreign Relations",
        "url": "https://www.cfr.org/rss/publications",
        "category": "politics",
        "source": "CFR",
        "emoji": "🗺️",
    },
    {
        "name": "Brookings Institution",
        "url": "https://www.brookings.edu/feed/",
        "category": "politics",
        "source": "Brookings",
        "emoji": "🏛️",
    },
    {
        "name": "Reuters Politics",
        "url": "https://feeds.reuters.com/reuters/politicsNews",
        "category": "politics",
        "source": "Reuters",
        "emoji": "📡",
    },
]

CATEGORIES = [
    {"id": "world", "name": "World", "emoji": "🌍", "color": "blue"},
    {"id": "technology", "name": "Technology", "emoji": "💻", "color": "purple"},
    {"id": "ai", "name": "AI", "emoji": "🤖", "color": "violet"},
    {"id": "science", "name": "Science", "emoji": "🧬", "color": "green"},
    {"id": "climate", "name": "Climate", "emoji": "🌱", "color": "emerald"},
    {"id": "business", "name": "Business", "emoji": "📊", "color": "amber"},
    {"id": "finance", "name": "Finance", "emoji": "💹", "color": "yellow"},
    {"id": "health", "name": "Health", "emoji": "❤️", "color": "rose"},
    {"id": "sports", "name": "Sports", "emoji": "⚽", "color": "orange"},
    {"id": "entertainment", "name": "Entertainment", "emoji": "🎬", "color": "pink"},
    {"id": "politics", "name": "Politics", "emoji": "🏛️", "color": "indigo"},
]
